name: idris2
base: core20
summary: A dependently typed programming language, a successor to Idris
description: |
  Idris 2 is a dependently typed programming language based on "Quantitative Type Theory"
  which allows explicit annotation of erased types, and linear types.
confinement: classic
adopt-info: idris2

architectures:
  - build-on: amd64

apps:
  idris2:
    command: bin/launcher

parts:
  launcher:
    plugin: nil
    source: src
    override-build: |
      idris2_part_install=$SNAPCRAFT_PART_INSTALL/../../idris2/install
      idris2_version=$(ls -t $idris2_part_install | grep idris2- | head -1)
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      sed "s/IDRIS2_VERSION=/IDRIS2_VERSION=$idris2_version/g" launcher.sh.in \
        > $SNAPCRAFT_PART_INSTALL/bin/launcher
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/launcher
    stage:
      - bin/launcher
    after: [idris2]
  chez:
    plugin: dump
    source: src/
    organize:
      chez.sh: bin/chez
    stage:
      - bin/chez
  idris2:
    plugin: make
    source: https://github.com/idris-lang/idris2.git
    source-tag: v0.3.0
    build-packages:
      - clang
      - chezscheme9.5
    stage-packages:
      - chezscheme9.5
    stage:
      - bin/idris2_app/idris2.so
      - lib
      - idris2-*
      - usr
    override-pull: |
      snapcraftctl pull
      version="$(git describe --tags --always | sed -e 's/-/+git/;y/-/./')"
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "devel"
    override-build: |
      export OPT=-O2
      export PATH=$SNAPCRAFT_PART_INSTALL/bin:$PATH
      export LD_LIBRARY_PATH=$SNAPCRAFT_PART_INSTALL/lib:$LD_LIBRARY_PATH

      # Boostrap and install
      make bootstrap SCHEME=chezscheme9.5 PREFIX=$SNAPCRAFT_PART_INSTALL
      make install PREFIX=$SNAPCRAFT_PART_INSTALL

      # Fix folder permissions
      find $SNAPCRAFT_PART_INSTALL/idris2* -type d -exec chmod 755 {} \;
