name: idris2
base: core18
summary: A dependently typed programming language, a successor to Idris
description: |
  A pre-alpha version of Idris 2. Idris 2 is a dependently typed programming language based
  on "Quantitative Type Theory" which allows explicit annotation of erased types, and linear types.
confinement: classic
adopt-info: idris2

architectures:
  - build-on: amd64

apps:
  idris2:
    command: bin/launcher $SNAP/bin/idris2

parts:
  launcher:
    plugin: nil
    source: src
    override-build: |
      idris2_part_install=$SNAPCRAFT_PART_INSTALL/../../idris2/install
      idris2_version=$(ls -t $idris2_part_install | grep idris2- | head -1)
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      sed "s/IDRIS2_VERSION=/IDRIS2_VERSION=$idris2_version/g" launcher.sh.in \
        > $SNAPCRAFT_PART_INSTALL/bin/launcher
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/launcher
    stage:
      - bin/launcher
    after: [idris2]
  chez:
    plugin: dump
    source: src/
    organize:
      chez.sh: bin/chez
    stage:
      - bin/chez
  idris2:
    plugin: make
    source: https://github.com/edwinb/idris2.git
    build-packages:
      - clang
      - chezscheme9.5
    stage-packages:
      - chezscheme9.5
    override-pull: |
      snapcraftctl pull
      version="$(git describe --always | sed -e 's/-/+git/;y/-/./')"
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "devel"
    override-build: |
      export PATH=$HOME/.cabal/bin:$PATH
      export OPT=-O2
      make install PREFIX=$SNAPCRAFT_PART_INSTALL
      # Fix folder permissions
      find $SNAPCRAFT_PART_INSTALL/idris2* -type d -exec chmod 755 {} \;
    after: [idris]
  idris:
    plugin: nil
    source: https://github.com/idris-lang/Idris-dev.git
    source-tag: v1.3.2
    build-packages:
      - wget
      - cabal-install
      - libffi-dev
      - pkg-config
      - zlib1g-dev
    override-build: |
      cabal --http-transport=wget update
      cabal --http-transport=wget install idris-1.3.2
