name: idris2
base: core18
version: 'pre-alpha'
summary: A dependently typed programming language, a successor to Idris
description: |
  A pre-alpha version of Idris 2. Idris 2 is a dependently typed programming language based
  on "Quantitative Type Theory" which allows explicit annotation of erased types, and linear types.
grade: devel
confinement: classic

apps:
  idris2:
    command: launcher $SNAP/bin/idris2

parts:
  launcher:
    plugin: dump
    source: src/
    organize:
      launcher.sh: bin/launcher
    stage:
      - bin/launcher
  idris2:
    plugin: make
    source: https://github.com/edwinb/idris2.git
    build-packages:
      - chezscheme
    stage-packages:
      - chezscheme
    override-build: |
      export PATH=/root/.cabal/bin:$PATH
      make install PREFIX=$SNAPCRAFT_PART_INSTALL
      # Fix folder permissions
      find $SNAPCRAFT_PART_INSTALL/idris2-0.0.0 -type d -exec chmod 755 {} \;
    after: [idris]
  idris:
    plugin: nil
    source: https://github.com/idris-lang/Idris-dev.git
    source-tag: v1.3.2
    build-packages:
      - cabal-install
      - libffi-dev
      - pkg-config
      - zlib1g-dev
    override-build: |
      cabal update
      cabal install idris-1.3.2
